# Generated by Django 3.1.1 on 2020-09-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('catagory', models.CharField(max_length=100)),
                ('translated', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('word_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
